name: frontend-cd

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  test_job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install packages
        run: npm ci
      - name: Run test
        run: npm run test
  build_job:
    name: Build job
    env:
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 193180914360
    runs-on: ubuntu-latest
    needs:
      - test_job
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - name: Extract git tag
        run: export GIT_SHA=$(git rev-parse master)
      - name: Build, tag, and push image to amazon ECR
        run: |
          docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:$GIT_SHA
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/frontend:$GIT_SHA