name: frontend-cd

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test_job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install packages
        run: npm ci
      - name: Run test
        run: npm run test
  build_job:
    name: Build job
    env:
      ECR_REGISTRY: <...>
      ECR_REPOSITORY: <...>
      AWS_REGION: <...>
    runs-on: ubuntu-latest
    needs:
      - test_job
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install packages
        run: npm ci
      - name: Login to AWS ECR
        run: 
      - name: Extract git tag
        run: export GIT_SHA=$(git rev-parse master)
      - name: Build, tag, and push image to amazon ECR
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_SHA